# Generated by Django 4.2.1 on 2023-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoccerAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.CharField(max_length=5),
        ),
    ]
